schema_version = "1.0.0"
id = "gp_auto_interpolate"
name = "GP Auto Interpolate"
version = "2.5.1"
tagline = "Grease Pencil Real-time Auto-Interpolation"
maintainer = "cosmosmythos"
type = "add-on"
tags = ["Grease Pencil", "Animation", "Geometry Nodes"]
blender_version_min = "4.3.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025- cosmosmythos"]
website = "https://cosmosmythos.gumroad.com/"
